[simulation_properties]
particles = 100
repetitions = 100000
minimization_iterations = 1000
temperature = 1.0e-3                           # Temperature in Kelvin
sigma = 1.1e-3                                 # Should be a value so that the acceptance rate is 50%
mass = 1.0
dipole_vector = [
    0.0,
    0.0,
    0.7071067811865476                         # sqrt 0.5
]
trapping_frequency_z = 50                      # 50 in Hz 
trapping_frequency_transverse = 1              # 1 in Hz
wall_repulsion_coefficient = 1.0e+0
sampling_rate = 5
blocking_transformation_number = 3
cutoff = 0                                     # cutoff * sample_rate is the iteration at which energies are discarded - be generous in choosing the value
bins_x = 100
bins_y = 100
bins_z = 1
order_repulsive_wall = 6
monte_carlo_read_configuration = false
output_basin_txt_file = true
output_pd_energy_and_coordinates_file = true
ground_state_coordinates_for_QMC = false
seed = 38479
